Create sample kubernetes deployment
jaroslawhartman/withings-sync pull request #18
Opened 2021-03-17 08:09 UTC by dbaker-rh

The contrib/ directory already has an example of using a kubernetes job to run the sync.  I've re-written it as a deployment and fixed a few minor issues (e.g. permitting to run as root by default, fully qualified container name, etc) along the way.

2021-03-17 12:27 UTC, stv0g commented
Hi @dbaker-rh,

thanks for your contribution :) I am wondering why you are using a deployment? Isn't the existing cronjob more adequate?

2021-03-18 09:09 UTC, dbaker-rh commented
I started updating the contributed job to better suit my needs, but had too much to tweak so started over with a deployment.

I think the deployment will handle things like logging much better than jobs, especially if you need to go back in time further to see when a problem started.

The only place I use jobs (and these are jobs, not cronjobs) in my cluster which handles tasks like this is in one-time, manual backup and restore jobs.  Everything else is a deployment -- scale it to zero to disable, scale back to one to enable.   I don't see the same flexibility being available here, so prefer to not use it.

2021-04-16 17:01 UTC, jaroslawhartman requested changes
Hi,

I have some doubts regarding sleep duration.

Can we set in the sample something longer, e.g. 24hrs?

Best regards,
Jarek

2021-04-17 11:39 UTC, dbaker-rh commented
24hrs seems excessive to me.  e.g. I weight myself at 9am and it doesn't sync until the following day.

I had chosen 15 minutes because that matched the existing kube cronjob example of 15 minutes, but once per hour would also (imho) be an entirely suitable cadence.

2021-06-03 08:34 UTC, merged